Supinic/supibot-package-manager

- commands/checkdeadchannels/index.js
- commands/coinflip/index.js
- commands/osrs/index.js
- commands/pipozdola/index.js
- commands/randomdoctordisrespect/index.js
- commands/videostats/index.js
Closes #1 ![FarmingCommits](https://cdn.betterttv.net/emote/5ed57f8bfdee545e3065efcb/1x)
> Refactored legacy commands to new code style

- commands/cookiecount/index.js
- commands/statistics/index.js
> Refactor the cc command into the stats cc

- commands/twitchlotto/index.js
> Retry twitchlotto image up to 3 times

- commands/schedule/index.js
> Fixes case insensitive string matching

- commands/songrequest/index.js
#14 
It's a one-liner? Am I missing something?
> Redirect no-args songrequest cmd to current cmd (Supinic#14)

- commands/songrequest/index.js
> Fixed the bug I made in #20 haha

- commands/corona/index.js
> Added active cases per million to corona command

- commands/emotecheck/index.js
> Add KPop emoteset to emotecheck

- commands/texttransform/index.js
Transforms text like in the [mocking spongebob meme](https://knowyourmeme.com/memes/mocking-spongebob).
I hope this works as intended (I'm new to JS, but tested it in the browser console with `Math.random`).
When `sb.Utils.random` gets a way to use a seed, you could make it deterministic for every input by using the input as seed.
> Added mocking spongebob meme to texttransform

- commands/news/index.js
Adds a Turkish news source for #36
> Add a Turkish news source

- commands/news/index.js
The old source had old news so I switched to another one.
> Change Turkish news source

- commands/api/index.js
<sup><sub>also adds a newline at the end of file</sub></sup>
> Add missing semicolon

- commands/cryptogame/index.js
- commands/forsenCD/index.js
- commands/news/index.js
> Use HTTPS where available

- commands/news/index.js
Now uses an endpoint with more domestic news.
> update turkish news source

- commands/randomscp/index.js
This command fetches a random SCP from the SCP Wiki 🤩 ([suggestion #2670](https://supinic.com/data/suggestion/2670))
<sup><sub>Forgot to escape commit message 🫢</sub></sup>
> Add $randomscp

- commands/dankdebug/create-sandbox.js
- commands/dankdebug/index.js
- commands/dankdebug/sandbox.d.ts
I initially planned to only add type definitions as some sort of documentation, but I added a description as well because I think its a helpful resource for those looking into it. Most of the meta-knowledge about the command exists from past discussions, experimentation, and reading the source. Now there is a helpful overview of (in my opinion) the most useful information about the command.
Feel free to change any of the wording/formatting for the description. I tried to match the style with other descriptions I looked at, including many examples.
> Add `.d.ts` type declarations and description for $js

- commands/news/definitions.json
Related: #36
Note: This is a news outlet based in Seoul.
> Added North Korean News

- commands/firstline/index.js
This would allow to search for the first line of a user in a specified channel (or, if non provided, the current channel)
Let me know what you think of this.
> Specify a channel as context for command "firstline" 

- commands/news/definitions.json
Related: https://github.com/Supinic/supibot-package-manager/issues/36
> Added Saudi Arabian News

- commands/commitcount/index.js
> Fix possible GQL injection for $commitcount

- commands/russianarmylosses/index.js
This command fetches the latest losses of the russian army from the https://russianwarship.rip API
This is how it looks in chat:
> implement russianarmylosses command
